spring:
  application.name: SWIGGY-GATEWAY
  cloud:
    gateway:
      routes:
      - id: swiggy-app
        uri: lb://SWIGGY-APP
        predicates:
          - Path=/swiggy/**
      - id: restaurant-service
        uri: lb://RESTAURANT-SERVICE
        predicates:
          - Path=/restaurant/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka